force-app/main/default/objects/Candidate_Profile__c/Candidate_Profile__c.object-meta.xml
<CustomObject>
    <label>Candidate Profile</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomTeams__Team_Members__c/CustomTeams__Team_Members__c.object-meta.xml
<CustomObject>
    <description>Used to store Team Members on a Team</description>
    <label>Team Members</label>
    <nameField>
        <displayFormat>M-{000}</displayFormat>
        <label>Member Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomTeams__Team_Members__c/fields/CustomTeams__Team__c.field-meta.xml
<CustomField>
    <fullName>CustomTeams__Team__c</fullName>
    <description>Used to map the team member to a team</description>
    <label>Team</label>
    <referenceTo>CustomTeams__Teams__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomTeams__Team_Members__c/fields/CustomTeams__User__c.field-meta.xml
<CustomField>
    <fullName>CustomTeams__User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Used to map a User to a Team</description>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>User is not active</errorMessage>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomTeams__Teams__c/CustomTeams__Teams__c.object-meta.xml
<CustomObject>
    <label>Teams</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomTeams__Teams__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Candidate_Profile__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate Profile</label>
    <referenceTo>Candidate_Profile__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Posting__c.field-meta.xml
<CustomField>
    <fullName>Job_Posting__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Posting</label>
    <referenceTo>Job_Posting__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Profile_Status__c.field-meta.xml
<CustomField>
    <fullName>Profile_Status__c</fullName>
    <label>Profile Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Client_Approval_Process__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Profile_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Profile_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Internal Submit</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Lead Approved</fullName>
            </value>
            <value>
                <fullName>Lead Rejected</fullName>
            </value>
            <value>
                <fullName>Client Approved</fullName>
            </value>
            <value>
                <fullName>Client Rejected</fullName>
            </value>
            <value>
                <fullName>On Interview Process</fullName>
            </value>
            <value>
                <fullName>L1 Interview Scheduled</fullName>
            </value>
            <value>
                <fullName>L1 Interview Approved</fullName>
            </value>
            <value>
                <fullName>L1 Interview Rejected</fullName>
            </value>
            <value>
                <fullName>L2 Interview Scheduled</fullName>
            </value>
            <value>
                <fullName>L2 Interview Approved</fullName>
            </value>
            <value>
                <fullName>L2 Interview Rejected</fullName>
            </value>
            <value>
                <fullName>Manager Round Scheduled</fullName>
            </value>
            <value>
                <fullName>Manager Round Approved</fullName>
            </value>
            <value>
                <fullName>Manager Round Rejected</fullName>
            </value>
            <value>
                <fullName>Interview Cleared</fullName>
            </value>
            <value>
                <fullName>Interview Rejected</fullName>
            </value>
            <value>
                <fullName>Document Verified</fullName>
            </value>
            <value>
                <fullName>Document Rejected</fullName>
            </value>
            <value>
                <fullName>Offer Letter</fullName>
            </value>
            <value>
                <fullName>Onboard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Postings</relationshipLabel>
    <relationshipName>Job_Postings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Job_OC_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_OC_Status__c</fullName>
    <label>Job OC Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/No_Of_Candidate_Selected__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Candidate_Selected__c</fullName>
    <label>No Of Candidate Selected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Notice_Period__c.field-meta.xml
<CustomField>
    <fullName>Notice_Period__c</fullName>
    <label>Notice Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Immediate</fullName>
            </value>
            <value>
                <fullName>0-15</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Posting_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Posting_Due_Date__c</fullName>
    <label>Posting Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Posting__c/fields/Teams__c.field-meta.xml
<CustomField>
    <fullName>Teams__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Teams</label>
    <referenceTo>CustomTeams__Teams__c</referenceTo>
    <relationshipLabel>Job Recruiter&apos;s</relationshipLabel>
    <relationshipName>Job_Recruiting_Team</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HomePageController.cls
public class HomePageController {
    
    @AuraEnabled        
    public static List<Job_Posting__c> getJobPosting(String companyFilter, String postStatus) {
        String currentUser = UserInfo.getUserId();
        system.debug('fetchdata :'+UserInfo.getUserId());
        /*String currentUserName = UserInfo.getName();
        system.debug('fetchdataName :'+UserInfo.getName());
        
        List<CustomTeams__Team_Members__c> userTeam =  [Select CustomTeams__Team__r.Name from CustomTeams__Team_Members__c where CustomTeams__User__r.Name =: currentUserName];
        system.debug('userTeam>>>'+userTeam);*/
        
        /*String qryJobPosting ='Select Teams__c,Name,Posting_Due_Date__c,No_Of_Candidate_Selected__c,Job_OC_Status__c from Job_Posting__c';
        String qryjobPostingWhereClause = ' ' ;
        system.debug('qryJobPosting'+qryJobPosting);
        
        for(Integer i=0; i<userTeam.size(); i++){
            qryjobPostingWhereClause+=' (Teams__r.Name =\''+userTeam[i]+'\')';
            system.debug('qryjobPostingWhereClause'+qryjobPostingWhereClause);
        }
        qryJobPosting = qryJobPosting+ qryjobPostingWhereClause ;
        system.debug('qryJobPosting'+qryJobPosting);
        
        List<Job_Posting__c> listOfValues = Database.query(qryJobPosting);  
        
        System.debug('listOfValues'+listOfValues);*/
        //   String companyFilter = 'Sony India';
        String querry = 'Select Account__r.Name, Teams__c,Name,Posting_Due_Date__c,No_Of_Candidate_Selected__c,Job_OC_Status__c from Job_Posting__c WHERE Id <> null ';
        if(String.isNotBlank(companyFilter)){
            querry+= ' AND Account__r.Name = :companyFilter';
        }
        if(String.isNotBlank(postStatus)){
            querry+= ' AND Job_OC_Status__c = :postStatus';
        }
        System.debug(LoggingLevel.DEBUG, querry+'####Querry final');
        List<Job_Posting__c> listOfValues = Database.query(querry);
        system.debug('listOfValues>>>'+listOfValues);
        //Added by Dharshan
        for(Job_Posting__c values : listOfValues){
            if(values.Posting_Due_Date__c != null){
                //Due Date
                DateTime dueDate = values.Posting_Due_Date__c;
                System.debug('Due Date>>'+dueDate);
                String dueDateStr1 = dueDate.format('yyyy-MM-dd');
                System.debug('Due Date>>'+dueDateStr1);
                //Today date
                DateTime todaysDate = System.today();
                String todaysDateStr = todaysDate.format('yyyy-MM-dd');
                System.debug('Today date>>'+todaysDateStr);
                
                if(todaysDateStr > dueDateStr1){
                    values.Job_OC_Status__c = 'Closed';
                }
                update values;
            }
        }
        //ENDED by Dharshan  
        
        List<Job_Posting__c> lstOfAddedList = new List<Job_Posting__c>();
        for(Job_Posting__c teamMember : listOfValues){
            List<CustomTeams__Team_Members__c> lstOfMember = [Select CustomTeams__User__c from CustomTeams__Team_Members__c where CustomTeams__Team__c =: teamMember.Teams__c];
            for(CustomTeams__Team_Members__c member : lstOfMember){
                system.debug('fetchdata :'+UserInfo.getUserId());
                system.debug('member.CustomTeams__User__c'+member.CustomTeams__User__c);
                if(member.CustomTeams__User__c == UserInfo.getUserId()){
                    lstOfAddedList.add(teamMember);
                    system.debug('lstOfAddedList>>'+lstOfAddedList);
                }
            }
        }
        system.debug('Job_Posting__c>>>'+listOfValues);
        return lstOfAddedList;
    }
    
    @AuraEnabled
    public static Map<String,String> getClientList(){
        
            Map<String,String> clientList = new Map<String,String>();
        List<Job_Posting__c> client = [SELECT Account__r.Name, Name FROM Job_Posting__c WHERE Account__r.Name <> null];
        for (Job_Posting__c data : client) {
            System.debug(data);
            System.debug(data.Account__r.Name);
            clientList.put(data.Account__r.Id, data.Account__r.Name);

        }
        System.debug((clientList));
        return clientList;
    }

    @AuraEnabled
    public static Map<String,String> getStatusList(){
           Schema.DescribeFieldResult statusfield = Job_Posting__c.Job_OC_Status__c.getDescribe();
        Map<String,String> statusList = getPickListValuesIntoMap(statusfield);
        return statusList;
    }

    public static Map<String,String> getPickListValuesIntoMap(Schema.DescribeFieldResult objval){
        Map<String,String> pickListValuesMap= new Map<String,String>();
        List<Schema.PicklistEntry> ple = objval.getPicklistValues();
        if(!(ple.isEmpty())){
            for (Schema.PicklistEntry var : ple) {
                pickListValuesMap.put((var.getValue()).toUpperCase(), (var.getLabel()).toUpperCase());
            }
        }
         return pickListValuesMap;
     }

    @AuraEnabled
    public static  List<Job_Posting__c> togetJobPostings(String companyFilter, String postStatus){
        //System.debug('items>>.'+items);
        String currenUser = UserInfo.getUserId();
        system.debug('currenUser>>>'+currenUser);

        List<Account> userAccnts = new List<Account>();
        userAccnts = [Select Name from Account where CreatedById =: currenUser];
        system.debug('userAccnts>>'+userAccnts);

        List<Job_Posting__c> jobPostings = [Select Id,Name,Posting_Due_Date__c,No_Of_Candidate_Selected__c,Job_OC_Status__c,(Select Name,Job_Posting__c,Candidate_Profile__r.Designation__c,Candidate_Profile__r.Experience__c,Candidate_Profile__r.Skills__c,Candidate_Profile__r.Current_Location__c,Candidate_Profile__r.Notice_Period__c,Profile_Status__c,Status__c from Job_Applications__r) from Job_Posting__c where  Account__c IN :userAccnts];
        system.debug('jobPostings>>'+jobPostings);
        return jobPostings;
    }
    
     public class JobApplicantsWrap
    {
        @AuraEnabled public List<string> StatusButtons ;
        @AuraEnabled public Job_Posting__c JobPosting = new Job_Posting__c();
    }
    
   
}